### ISSUE TITLE
No AoT support

### ISSUE THREAD

**Issue by dotMorten** [nohwnd/mstest-runner-examples#1]
One of my biggest griefs with MSTest is I can't test if my stuff works right in an AoT build.
Try building your project with `dotnet publish -c Release -p PublishAot=true -r win-x64` and run it, and you'll get loads of build warnings, and a runtime crash.

Now I understand why it currently doesn't work (too much reflection and datacontract serializers), but solving this would be huge for ensuring AoT compatibility.

It would likely require a little code generator for each `TestMethod` attribute instead of relying on reflection discovery, and using the new System.Text.Json serializers.

**Comment by nohwnd** [comment]
We plan to merge microsoft.testing.testframework which hosts a framework that does just that (is native aot compatible) with mstest, and run it via microsoft.testing.platoform (which already is nativeaot compatible). But if you have ideas how to do it all in simple way (even if ignoring the current testing platform), then I am all ears :)

**Comment by nohwnd** [comment]
Moved the discussion here: https://github.com/microsoft/testfx/issues/1837
